[package]
name = "msgtrans"
version = "0.1.4"
edition = "2021"
authors = ["zoujiaqing <zoujiaqing@gmail.com>"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/zoujiaqing/msgtrans-rust"
categories = ["asynchronous", "network-programming"]
keywords = ["tcp", "udp", "quic", "websocket", "tokio"]
description = "Support for a variety of communication protocols such as TCP / QUIC / WebSocket, easy to create server and client network library."

[dependencies]
tokio = { version = "1.32", features = ["full"] }
tokio-tungstenite = "0.19"
s2n-quic = { version = "1" }
async-trait = "0.1.64"
futures = "0.3.28"
bytes = "1.4.0"
url = "2.4.0"
crossbeam = "0.8"
anyhow = "1"
flate2 = "1"
zstd = "0.13"