[package]
name = "msgtrans-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.32", features = ["full"] }
tokio-tungstenite = "0.19"
async-trait = "0.1.64"
futures = "0.3.28"
bytes = "1.4.0"
url = "2.4.0"
crossbeam = "0.8"
