[package]
name = "msgtrans"
version = "0.1.1"
edition = "2021"
description = "Support for a variety of communication protocols such as TCP / QUIC / WebSocket, easy to create server and client network library."
license = "Apache-2.0"

[dependencies]
tokio = { version = "1.32", features = ["full"] }
tokio-tungstenite = "0.19"
s2n-quic = { version = "1" }
async-trait = "0.1.64"
futures = "0.3.28"
bytes = "1.4.0"
url = "2.4.0"
crossbeam = "0.8"
anyhow = "1"
flate2 = "1"
zstd = "0.13"